const images = {
  hampr: require('../Images/hampr.png'),
  folded: require('../Images/folded.png'),
  location: require('../Images/location.png'),
  phone: require('../Images/phone.png'),
  washr: require('../Images/washer.png'),
  show: require('../Images/show.png'),
  lock: require('../Images/lock.png'),
  logo: require('../Images/washr.png'),
  route: require('../Images/route.png'),
  pickUp: require('../Images/pick_up.png'),
  password: require('../Images/password.png'),
  locationBg: require('../Images/locationBg.png'),
  avatar: require('../Images/avatar.png'),
  orders: require('../Images/orders.png'),
  ordersUnselected: require('../Images/ordersUnselected.png'),
  myOrders: require('../Images/my_orders.png'),
  myOrdersUnselected: require('../Images/my_ordersUnselected.png'),
  close: require('../Images/close.png'),
  closeWhite: require('../Images/closeWhite.png'),
  backArrow: require('../Images/back_arrow.png'),
  overflow: require('../Images/overflow.png'),
  downArrow: require('../Images/down_arrow.png'),
  location_small: require('../Images/location-small.png'),
  call: require('../Images/call.png'),
  text: require('../Images/text.png'),
  star: require('../Images/star_empty.png'),
  forwardArrow: require('../Images/forward_arrow.png'),
  scan: require('../Images/scan.png'),
  qrOverlay: require('../Images/qr_scanner.png'),
  drop: require('../Images/drop.png'),
  edit: require('../Images/edit.png'),
  dropps: require('../Images/dropps.png'),
  preferences: require('../Images/preferences.png'),
};

export default images;
